name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore src/
      - name: Build
        run: dotnet build src/ --no-restore
      - name: Test with coverage
        run: dotnet test src/ --no-build --collect:"XPlat Code Coverage"
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: List coverage files
        run: find . -name "coverage.cobertura.xml"
      - name: Create coverage directory
        run: mkdir -p coverage
      - name: Generate coverage report
        run: reportgenerator -reports:./src/**/TestResults/**/coverage.cobertura.xml -targetdir:coverage -reporttypes:Cobertura
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/Cobertura.xml
          coveralls-endpoint: https://coveralls.io
